### ISSUE TITLE
Directory Restructure?

### ISSUE THREAD

**Issue by jbkoh** [MetroInsight/citadel#1]
Hi all,

Before I decide where to put my module in the project, I'd like to restructure the current directory structure.

- Currently rest_api.py contains all the REST APIs (hypothetically). Each module that would reside under our app will have to implement REST interfaces (corresponding to view), which is colliding when multiple developers develop their modules. Shouldn't we separate out to individual modules?
(ref: https://www.digitalocean.com/community/tutorials/how-to-structure-large-flask-applications)

- Moving MongoDB initiation into the specific module for metadata for modularization.

I have updated above issues in my local repository and am ready to push to the repo. If no objections, I will push it to the repo.

**Comment by jbkoh** [comment]
Also, who is dependent on this change currently?

**Comment by bbalaji-ucsd** [comment]
I’m the only one who would care about this change at this stage.

I’d like to discuss this further, but won’t have time until 9pm today.
Sorry to keep you waiting.

On Wed, Feb 15, 2017 at 2:05 AM, Jason Beomkyu Koh <notifications@github.com

**Comment by jbkoh** [comment]
Also, Point and Metadata are not separable (currently they are embedded together anyway), so Can we remove Metadata part and shall I just develop Point?

**Comment by bbalaji-ucsd** [comment]
metadata.py currently doesn't have anything, so can be deleted. Updating tags for a single point can go under point.py as you suggested.

Let's wait till we decide exactly what are the different modules that can be separated before creating folders for them.
