### ISSUE TITLE
Branch clean-up

### ISSUE THREAD

**Issue by jbkoh** [MetroInsight/citadel#4]
There is no meaning in the current branch setup. I will move dev-api to master once my PR is merged.

**Comment by bbalaji-ucsd** [comment]
Yes, I agree. You made a pull request? You can just merge it if you already
did the development.

We can discuss issues over GitHub if needed, or you could put down your
plan of development before you code it up. This is just to ensure your
coding effort doesn’t go through many revisions.

We can come back to more formal pull request when we have more activity or
chances of conflicts.

**Comment by jbkoh** [comment]
done.
