### ISSUE TITLE
geoquery does not return valid geojson

### ISSUE THREAD

**Issue by crawld** [MetroInsight/citadel#8]
Here's an example geojson object containing multiple features:

https://tools.ietf.org/html/rfc7946#section-1.5

**Comment by jbkoh** [comment]
The current format is a correct model for 'Point': reference: http://geojson.org/

**Comment by crawld** [comment]
the returned object i see is a dictionary containing point_list, which is an array formatted like:

{
            "uuid": "a77c3846-6bd3-4938-8deb-ac91331135ad",
            "geometry": {
                "coordinates": [
                    -117.239422,
                    32.88055
                ],
                "type": "Point"
            },
            "name": "NorthCamp.Cog_Sci_B_E1322_RealTime:Real Power",
            "tags": {
                "unit": "KW",
                "point_type": "electrical power",
                "source_reference": "ucsd_ion"
            }
        }

the geometry field is correct, but everything else should go into a "properties" dict. there should also be a type: "Feature" at the same level as geometry.

**Comment by jbkoh** [comment]
closing as we do not use GeoJson for now.
